Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2019-10, with the labels that each got.

#10 Switch to go 1.13
  README.adoc
  go.mod
  go.sum
Labels: size/S

#8 chore: install newer git and allow unrelated histories while merging
  make/test.mk
  openshift-ci/Dockerfile.tools
Labels: size/S

#9 chore(CRT-229): deploy and install host operator via catalog
  README.adoc
  make/test.mk
Labels: size/M

#11 Move e2e tests to test/e2e dir
  make/test.mk
  test/e2e/doc.go
  test/e2e/e2e_test.go
  test/e2e/kubefed_test.go
  test/e2e/main_test.go
  test/e2e/usersignup_test.go
Labels: size/XS

#13 chore: make the test setup output cleaner
  make/test.mk
Labels: size/S

#15 fix: handle makefile replacement of dollar sign $ and don't commit while merging
  make/test.mk
Labels: size/XS

#16 fix: when it is executed from remote repo, then don't pair
  make/test.mk
Labels: size/M

#14 verify that NSTemplateTier are created/updated at startup
  .yamllint
  go.mod
  go.sum
  make/test.mk
  test/e2e/e2e_test.go
  test/e2e/nstemplatetier-basic.yaml
  test/e2e/nstemplatetier_test.go
  test/e2e/usersignup_test.go
  wait/host.go
Labels: size/L

#17 chore: add wait for CRD,improve logging and tag of local images
  make/test.mk
  wait/awaitility.go
Labels: size/S

#18 chore(CRT-226): deploy and install member-operator via CSV
  make/test.mk
Labels: size/S

#19 Fixed tests for new UserSignup.CompliantUsername field
  go.mod
  go.sum
  test/e2e/usersignup_test.go
Labels: size/M

#5 e2e test for NSTemplateSet ctrl
  doubles/init.go
  go.mod
  go.sum
  test/e2e/e2e_test.go
  test/e2e/nstemplateset_test.go
  wait/awaitility.go
  wait/member.go
Labels: size/L

#21 configure golangci-lint
  .golangci.yml
  make/lint.mk
Labels: size/S

#22 update clone path to include repo org
  make/test.mk
Labels: size/XS

#23 chore: increase wait limit for resources after deployment
  make/test.mk
Labels: size/XS

#25 chore: when initial operator setup fails then print deployment logs
  make/test.mk
Labels: size/S

#12 deploy reg service for e2e test setup
  make/test.mk
  openshift-ci/Dockerfile.registration.deploy
Labels: size/M

#24 Updated e2e tests to remove UserSignup.Spec.UserID
  go.mod
  go.sum
  test/e2e/usersignup_test.go
Labels: size/M

#27 fix: use correct images when triggered from reg-service repo
  README.adoc
  make/test.mk
Labels: size/M

#26 add smoke test for the registration service
  doubles/init.go
  go.mod
  go.sum
  make/test.mk
  test/e2e/e2e_test.go
  test/e2e/kubefed_test.go
  test/e2e/nstemplateset_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/registration_service_test.go
  test/e2e/usersignup_test.go
  wait/awaitility.go
Labels: size/L

#28 rename pkg 'doubles' to 'testsupport'
  test/e2e/e2e_test.go
  test/e2e/kubefed_test.go
  test/e2e/nstemplateset_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/registration_service_test.go
  test/e2e/usersignup_test.go
  testsupport/doubles.go
  testsupport/init.go
Labels: size/M
