Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2019-12, with the labels that each got.

#53 chore(CRT-361): reg-service SA and namespace name is moved to deployment
  make/test.mk
Labels: approved, size/XS

#54 Remove deprecated TargetCluster from MUR status
  go.mod
  go.sum
Labels: approved, size/M

#52 Removed workaround for token timestamp issue
  test/e2e/registration_service_test.go
Labels: approved, size/XS

#59 Annotations
  go.mod
  go.sum
  test/e2e/e2e_test.go
  test/e2e/registration_service_test.go
  test/e2e/usersignup_test.go
Labels: approved, size/M

#60 fix: fail if multiple branches are found
  make/test.mk
Labels: approved, size/S

#62 Grant users admin role
  make/test.mk
  test/e2e/e2e_test.go
Labels: approved, size/XS

#61 fix: fail if multiple branches for pairing are detected
  make/test.mk
Labels: approved, size/S

#63 Reduce user permissions
  test/e2e/e2e_test.go
  wait/member.go
Labels: approved, size/M
