Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2019-11, with the labels that each got.

#33 Switch to go 1.13 in builder image
  openshift-ci/Dockerfile.tools
Labels: size/S

#35 Install gcc in Dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: size/XS

#34 fix: clean properly the cluster
  make/test.mk
Labels: size/XS

#32 Switch to kube 1.14
  go.mod
  go.sum
  make/test.mk
  wait/awaitility.go
  wait/member.go
Labels: size/L

#37 Use OpenShift template to deploy reg-service
  make/test.mk
  wait/awaitility.go
Labels: size/XS

#38 Add OWNERS
  OWNERS
Labels: size/S

#31 refactor WaitForXYZ funcs
  test/e2e/e2e_test.go
  test/e2e/nstemplateset_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/usersignup_test.go
  testsupport/cleanup_options.go
  wait/awaitility.go
  wait/host.go
  wait/member.go
Labels: approved, size/XL

#41 chore: don't clean cluster after successful test
  make/test.mk
Labels: approved, size/S

#43 fix: use new instance when getting resources in wait functions
  test/e2e/e2e_test.go
  wait/host.go
  wait/member.go
Labels: approved, size/M

#42 Add makefile targets to deploy e2e resources without running tests
  README.adoc
  make/dev.mk
  make/test.mk
Labels: approved, size/M

#44 Print Landing Page URL when deploying to dev env
  make/dev.mk
  make/test.mk
Labels: approved, size/M

#30 add e2e test for signup->namespaces
  test/e2e/conditions.go
  test/e2e/e2e_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/usersignup_test.go
  wait/awaitility.go
  wait/host.go
  wait/member.go
Labels: approved, size/L

#45 Properly pass variables when running dev-deploy targets
  make/dev.mk
Labels: approved, size/M

#29 Refactored usage of UserSignup.Spec.CompliantUsername
  go.mod
  go.sum
  test/e2e/e2e_test.go
  test/e2e/usersignup_test.go
Labels: approved, size/L

#46 Allow individual tests override wait timeouts and retry intervals
  test/e2e/usersignup_test.go
  testsupport/init.go
  wait/awaitility.go
  wait/host.go
  wait/member.go
Labels: approved, size/L

#47 Cleanup UserSignup tests
  test/e2e/conditions.go
  test/e2e/e2e_test.go
  test/e2e/nstemplateset_test.go
  test/e2e/usersignup_test.go
  wait/host.go
  wait/member.go
Labels: approved, size/XL

#50 makefile goal to display the latest e2e project names
  make/test.mk
Labels: approved, size/S

#49 Tests for Namespaces and RoleBindings in NS Templates
  make/test.mk
  test/e2e/e2e_test.go
  wait/awaitility.go
  wait/member.go
Labels: approved, size/L

#48 E2e tests registration service
  go.mod
  go.sum
  test/e2e/e2e_test.go
  test/e2e/registration_service_test.go
Labels: approved, size/L

#51 Tests for Console URL
  go.mod
  go.sum
  test/e2e/e2e_test.go
  test/e2e/registration_service_test.go
  wait/host.go
  wait/member.go
Labels: approved, size/L
