Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2020-01, with the labels that each got.

#64 Add `toolchain.dev.openshift.com/` prefix to namespace labels
  .gitignore
  test/e2e/nstemplateset_test.go
  wait/member.go
Labels: approved, size/S

#67 chore: install github.com/kislyuk/yq binary
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#65 feat(CRT-363): load config env files using enrich-by-envs-from-yaml.sh script
  make/test.mk
Labels: approved, size/S

#69 feat: select first member cluster ready and with capacity
  go.mod
  make/dev.mk
  test/e2e/kubefed_test.go
  testsupport/init.go
  wait/awaitility.go
  wait/member.go
Labels: approved, size/L

#70 chore: use ${QUAY_NAMESPACE} prefix/suffix for namespaces and subscriptions
  make/dev.mk
  make/test.mk
Labels: approved, size/S

#56 feat(CRT-354): let host-operator deploy the registration service
  make/dev.mk
  make/test.mk
  testsupport/init.go
Labels: approved, size/M
