Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2020-02, with the labels that each got.

#72 add test to verify that namespaces are recreated by member operator controller
  test/e2e/e2e_test.go
  wait/host.go
  wait/member.go
Labels: approved, size/M

#71 chore: use digest instead of tags
  make/test.mk
Labels: approved, size/S

#73 fixing tests
  go.mod
  go.sum
  test/e2e/e2e_test.go
  test/e2e/usersignup_test.go
  wait/member.go
Labels: approved, size/M

#74 Update to Kube 1.16.2
  go.mod
  go.sum
Labels: approved, size/XL
