Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2020-03, with the labels that each got.

#75 Disabling useraccount
  go.mod
  go.sum
  test/e2e/conditions.go
  test/e2e/user_management_test.go
Labels: approved, do-not-merge/work-in-progress, size/L

#76 chore(CRT-474): verify that we can promote to other tier and back
  test/e2e/e2e_test.go
  test/e2e/nstemplateset_test.go
  test/e2e/user_management_test.go
  wait/member.go
Labels: approved, size/L

#77 chore(CRT-475): verify team tier
  test/e2e/e2e_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/user_management_test.go
  wait/member.go
Labels: approved, size/L

#81 add assertion on NSTemplateTier.spec.clusterResource
  go.mod
  go.sum
  test/e2e/nstemplatetier-basic.yaml
  test/e2e/nstemplatetier_test.go
  wait/host.go
Labels: approved, size/L

#80 Add user management e2e tests
  go.mod
  go.sum
  test/e2e/base_user_test.go
  test/e2e/conditions.go
  test/e2e/e2e_test.go
  test/e2e/user_management_test.go
  test/e2e/usersignup_test.go
  testsupport/md5/hashcalc.go
  wait/host.go
Labels: approved, size/XL

#79 feat: verify that ChangeTierRequest changes the tier
  go.sum
  test/e2e/base_user_test.go
  test/e2e/e2e_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/user_management_test.go
  test/e2e/usersignup_test.go
  tiers/checks.go
  tiers/nstemplateset.go
  tiers/revisions.go
  wait/host.go
Labels: approved, size/XL

#82 add limit ranges on namespace templates
  tiers/checks.go
  wait/member.go
Labels: approved

#83 Isolate pods in user namespaces
  tiers/checks.go
  wait/member.go
Labels: approved

#84 chore: verify role name rbac-edit
  tiers/checks.go
Labels: approved

#86 fix: verify revisions of ClusterResources
  make/test.mk
  test/e2e/e2e_test.go
  tiers/nstemplateset.go
  tiers/revisions.go
Labels: approved

#87 Update operator-sdk
  openshift-ci/Dockerfile.tools
Labels: approved
