Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2021-03, with the labels that each got.

#245 e2e tests for the 'user accounts per member cluster' metric
  go.mod
  go.sum
  make/perf.mk
  test/e2e/base_user_test.go
  test/e2e/e2e_test.go
  test/e2e/user_management_test.go
  test/e2e/user_workloads_test.go
  test/e2e/usersignup_test.go
  testsupport/init.go
  testsupport/metrics.go
Labels: approved

#249 refactor/cleanup packages
  make/go.mk
  test/e2e/base_user_test.go
  test/e2e/e2e_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/registration_service_test.go
  test/e2e/toolchaincluster_test.go
  test/e2e/user_management_test.go
  test/e2e/user_workloads_test.go
  test/e2e/usersignup_test.go
  test/perf/perf_test.go
  testsupport/init.go
  testsupport/metrics_server_assertions.go
  testsupport/tier_setup.go
  testsupport/tiers/checks.go
  testsupport/tiers/nstemplateset.go
  testsupport/tiers/templaterefs.go
  testsupport/toolchain_status_assertions.go
  testsupport/user_assertions.go
  testsupport/user_setup.go
  testsupport/wait/awaitility.go
  testsupport/wait/host.go
  testsupport/wait/member.go
  testsupport/wait/metrics.go
  testsupport/wait/metrics_test.go
  testsupport/wait/templateref_split.go
  version/version.go
Labels: approved

#247 Auto approval tests using multiple member clusters
  test/e2e/usersignup_test.go
Labels: approved

#253 Add setup instructions for onboarding
  make/clean.mk
  make/dev.mk
  setup/README.adoc
Labels: approved

#254 fix: double the timeout of the wait for webhook deployment
  testsupport/wait/member.go
Labels: approved

#255 Update README.adoc
  setup/README.adoc
Labels: approved

#258 Add member-operator-webhook quay repo to be set public into Prereqs instructions
  setup/README.adoc
Labels: approved, needs-ok-to-test

#257 refactor: use OpenShift template when provisioning users
  go.mod
  go.sum
  setup/README.adoc
  setup/cmd/root.go
  setup/configuration/configuration.go
  setup/idlers/update_idler.go
  setup/resources/create_resources.go
  setup/resources/create_resources_test.go
  setup/resources/user-workloads.yaml
  setup/resources/wait.go
  setup/resources/wait_test.go
  setup/sample/user-workloads.yaml
  setup/user/resources.go
  setup/user/user.go
  setup/users/create_users.go
  setup/users/create_users_test.go
Labels: approved

#261 Add precise param for users with template applied and update template
  setup/cmd/root.go
  setup/resources/user-workloads.yaml
Labels: approved

#264 chore: increase cpu limit to 20 cores
  testsupport/tiers/checks.go
Labels: approved

#263 Create more rolebindings and CSVs during setup
  go.mod
  setup/README.adoc
  setup/cmd/root.go
  setup/configuration/configuration.go
  setup/operators/install_operators.go
  setup/operators/install_operators_test.go
  setup/resources/user-workloads.yaml
  setup/resources/wait.go
  setup/resources/wait_test.go
  setup/test/fakeclient.go
Labels: approved, lgtm

#266 Add verify ToolchainStatus step and fix formatting
  setup/README.adoc
Labels: approved

#267 Adding e2e tests for adding apiEndpoint
  go.mod
  go.sum
  test/e2e/e2e_test.go
  testsupport/toolchain_status_assertions.go
  testsupport/wait/host.go
Labels: approved

#270 e2e test updated to check apiEndpoint is returned by Registration Service's signup service
  test/e2e/registration_service_test.go
Labels: approved

#271 feat: add posibility to deploy dev env without second member
  make/dev.mk
  make/test.mk
Labels: approved
