Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2021-04, with the labels that each got.

#273 Split setup template
  setup/README.adoc
  setup/cmd/root.go
  setup/resources/create_resources.go
  setup/resources/create_resources_test.go
Labels: approved

#268 Base tier e2e tests
  test/e2e/nstemplatetier_test.go
  testsupport/tiers/checks.go
  testsupport/wait/member.go
Labels: approved

#275 fix env var in multicluster setup
  multicluster_setup.adoc
Labels: approved

#272 chore: verify that users with specific suffixes are not created
  test/e2e/usersignup_test.go
Labels: approved

#277 Update tests to use base tier as default
  test/e2e/base_user_test.go
  test/e2e/e2e_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/registration_service_test.go
  test/e2e/user_management_test.go
  test/e2e/usersignup_test.go
  testsupport/conditions.go
  testsupport/tier_setup.go
  testsupport/user_assertions.go
  testsupport/user_setup.go
  testsupport/wait/host.go
Labels: approved

#278 Remove code namespaces from idler setup
  setup/idlers/update_idler.go
Labels: approved

#276 Clarify the note about always adding default template.
  setup/README.adoc
Labels: approved, lgtm, needs-ok-to-test

#279 Updated e2e tests for removed code NS for advanced and test tiers
  test/e2e/nstemplatetier_test.go
  testsupport/tiers/checks.go
Labels: approved

#280 Create a README for installing the Dev Sandbox in a development environment
  README.adoc
  dev_install.adoc
  required_tools.adoc
  setup/README.adoc
Labels: approved

#281 Add remove self-provisioner step
  dev_install.adoc
Labels: approved

#282 Add support for mutil-architecture
  make/go.mk
Labels: approved, ok-to-test

#284 doc: improve multi-cluster setup doc
  multicluster_setup.adoc
Labels: approved

#274 metrics: add field to store metrics in ToolchainStatus
  go.mod
  go.sum
  test/e2e/base_user_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/registration_service_test.go
  test/e2e/user_management_test.go
  test/e2e/usersignup_test.go
  testsupport/metrics.go
  testsupport/user_assertions.go
  testsupport/user_setup.go
  testsupport/wait/awaitility.go
  testsupport/wait/host.go
Labels: approved

#285 chore: verify RHOAS limits
  testsupport/tiers/checks.go
  testsupport/wait/member.go
Labels: approved

#283 Onboarding setup tool improvements
  go.mod
  setup/README.adoc
  setup/cmd/root.go
  setup/resources/create_resources.go
  setup/resources/create_resources_test.go
Labels: approved
