Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2022-03, with the labels that each got.

#490 fix: capture metric baseline values from both members
  test/e2e/toolchainstatus_test.go
  test/metrics/metrics_test.go
  testsupport/metrics.go
Labels: approved

#491 feat: support OSD in dev deployment
  dev_install.adoc
  make/dev.mk
  make/test.mk
Labels: approved

#489 minor changes in logging to identify failing object
  testsupport/cleanup/clean.go
Labels: approved

#488 Fix flaky test
  test/e2e/space_cleanup_test.go
  testsupport/wait/host.go
Labels: approved, lgtm

#492 Added test to ensure identity and user resources deleted correctly
  test/e2e/e2e_test.go
Labels: approved

#472 Added tests for signup endpoint update
  test/e2e/registration_service_test.go
Labels: approved

#475 Test migration from MUR to Spaces
  test/e2e/e2e_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/proxy_test.go
  test/e2e/space_cleanup_test.go
  test/e2e/space_test.go
  test/e2e/user_management_test.go
  test/metrics/metrics_test.go
  test/migration/setup_runner.go
  test/migration/verify/verify_migration_test.go
  testsupport/conditions.go
  testsupport/deactivation.go
  testsupport/space.go
  testsupport/spacebinding.go
  testsupport/tier_setup.go
  testsupport/tiers/nstemplateset.go
  testsupport/user_assertions.go
  testsupport/wait/host.go
  testsupport/wait/member.go
Labels: approved

#496 skip space cleanup test
  test/e2e/space_cleanup_test.go
Labels: approved

#497 Revert "skip space cleanup test"
  test/e2e/space_cleanup_test.go
Labels: approved

#495 fix(flaky-tests): wait until ToolchainStatus is updated
  test/e2e/e2e_test.go
  test/e2e/space_autocompletion_test.go
  test/e2e/usersignup_test.go
  testsupport/wait/host.go
Labels: approved

#487 feat: update k8s to v0.22.7 and OpenShift to 4.9
  go.mod
  go.sum
  required_tools.adoc
  test/e2e/user_management_test.go
  testsupport/wait/host.go
Labels: approved

#494 Add test for gitopsdeployments to appstudio-user-actions role
  testsupport/tiers/checks.go
  testsupport/wait/member.go
Labels: approved, ok-to-test

#493 test: skip SpaceRoles test for now
  go.mod
  go.sum
  test/e2e/space_test.go
Labels: approved

#505 feat: use must-gather
  make/test.mk
Labels: approved

#500 Test for codeready-toolchain/host-operator#610
  testsupport/tiers/checks.go
Labels: approved, needs-ok-to-test

#506 Drop counts for objects defined by CRDs from user quotas
  testsupport/tiers/checks.go
Labels: approved

#508 fix: install members first
  make/test.mk
  testsupport/wait/awaitility.go
Labels: approved

#503 e2e tests for users creating rolebinding with wider access
  make/clean.mk
  test/e2e/user_rolebindings_test.go
Labels: approved

#509 Add WTO/CRW NetworkPolicy to -stage
  testsupport/tiers/checks.go
Labels: approved

#499 Tests for new single namespace tier
  test/e2e/nstemplatetier_test.go
  testsupport/tiers/checks.go
Labels: approved

#517 Install rhoda and update other operator versions
  setup/README.adoc
  setup/operators/installtemplates/devworkspace-operator.yaml
  setup/operators/installtemplates/gitops-primer-template.yaml
  setup/operators/installtemplates/kiali.yaml
  setup/operators/installtemplates/rhoas.yaml
  setup/operators/installtemplates/rhoda.yaml
  setup/operators/installtemplates/sbo.yaml
  setup/operators/installtemplates/serverless-operator.yaml
  setup/operators/operators.go
Labels: approved

#504 feat: upgrade GH Actions env to Ubuntu 20.04
  .github/workflows/publish-operators-for-e2e-tests.yml
Labels: approved

#515 fix: get rid of reg-service flakiness
  make/dev.mk
  make/test.mk
  testsupport/wait/awaitility.go
Labels: approved
