Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2022-10, with the labels that each got.

#613 Use working set memory metric for perf testing
  setup/cmd/root.go
  setup/metrics/queries/query.go
Labels: approved

#614 Fix flaky registration service tests
  test/e2e/parallel/registration_service_test.go
Labels: approved

#612 Updating tests for updates to base1ns tier.
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#608 build: upgrade Go 1.17 and k8s.io v0.23.5
  .github/workflows/ci-build.yml
  .github/workflows/publish-operators-for-e2e-tests.yml
  README.adoc
  go.mod
  go.sum
  make/go.mk
  openshift-ci/Dockerfile.tools
  required_tools.adoc
  test/perf/perf_test.go
Labels: approved

#615 Update imagestream in default user-workloads
  setup/resources/user-workloads.yaml
Labels: needs-ok-to-test

#609 Removed migration test
  test/e2e/usersignup_test.go
Labels: approved

#616 Tests for base1ns6didler tier
  test/e2e/nstemplatetier_test.go
  testsupport/tiers/checks.go
Labels: approved
