Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2022-02, with the labels that each got.

#465 chore: verify that Space has state label set
  go.mod
  go.sum
  make/test.mk
  test/e2e/space_test.go
  test/migration/verify/verify_migration_test.go
  testsupport/space.go
  testsupport/wait/awaitility.go
  testsupport/wait/host.go
Labels: approved

#468 chore: verify SPI resources in appstudio-user-actions role
  testsupport/tiers/checks.go
Labels: approved

#457 feat: use env var to decide if it should use local scripts
  make/run-cicd-script.mk
Labels: approved

#467 refactoring: unify space functions
  test/e2e/nstemplatetier_test.go
  test/e2e/space_test.go
  test/e2e/spacebinding_test.go
  test/migration/setup_runner.go
  testsupport/space.go
  testsupport/wait/host.go
Labels: approved

#470 Provide current user namespace value that can be used in templates
  setup/resources/create_resources.go
Labels: approved

#469 Verify SpaceCompletion controller
  test/e2e/space_autocompletion_test.go
  test/e2e/space_test.go
  testsupport/space.go
Labels: approved

#471 Add query for kube-apiserver
  setup/metrics/gather.go
  setup/metrics/queries/query.go
Labels: approved

#473 Updated SBO channel and version
  setup/operators/installtemplates/sbo.yaml
Labels: approved, lgtm, ok-to-test

#474 add provider label check to user and identity provisioning
  testsupport/user_assertions.go
  testsupport/wait/member.go
Labels: approved

#476 verify that User resource has email annotation
  go.mod
  go.sum
  testsupport/user_assertions.go
  testsupport/wait/member.go
Labels: approved

#478 fix diff when ClusterResourceQuota does not match
  testsupport/tiers/checks.go
Labels: approved

#477 chore: include quota for SBO spec API
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#481 chore: Add interactive cli option
  setup/cmd/root.go
Labels: approved, ok-to-test

#482 Add delete for spiaccesstokenbindings in appstudio tier
  testsupport/tiers/checks.go
Labels: approved

#479 verify SpaceCleanup controller
  test/e2e/nstemplatetier_test.go
  test/e2e/space_autocompletion_test.go
  test/e2e/space_cleanup_test.go
  test/e2e/space_test.go
  test/e2e/spacebinding_test.go
  test/migration/setup_runner.go
  testsupport/signup_request.go
  testsupport/space.go
  testsupport/spacebinding.go
  testsupport/wait/host.go
Labels: approved

#483 refactor: improve the flow of the space_cleanup_test.go
  test/e2e/space_cleanup_test.go
  testsupport/space.go
Labels: approved

#485 Fix e2e tests with userID encoding change
  go.mod
  go.sum
  test/e2e/registration_service_test.go
  testsupport/user_assertions.go
  testsupport/wait/member.go
Labels: approved
