Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2022-09, with the labels that each got.

#592 test(appstudio/proxy): permissions to create TokenRequest API
  testsupport/tiers/checks.go
Labels: approved

#594 errors is
  test/e2e/proxy_test.go
Labels: approved

#599 Install Intel AIKit and OpenVino Operators.
  setup/operators/installtemplates/aikit.yaml
  setup/operators/installtemplates/openvino.yaml
  setup/operators/operators.go
Labels: approved, ok-to-test

#598 Install RHODS
  setup/operators/installtemplates/rhods.yaml
  setup/operators/operators.go
Labels: needs-ok-to-test

#601 Update other operators startingCSV to speed up installations
  setup/operators/installtemplates/devworkspace-operator.yaml
  setup/operators/installtemplates/gitops-primer-template.yaml
  setup/operators/installtemplates/serverless-operator.yaml
  setup/operators/installtemplates/web-terminal-operator.yaml
Labels: approved

#597 test: webhook to prevent users from creating CheCluster resources
  testsupport/wait/member.go
Labels: approved

#603 test: more strict assertion on webhook configuration
  testsupport/wait/member.go
Labels: approved

#605 Add dev spaces to perf setup tool
  setup/operators/installtemplates/devspaces.yaml
  setup/operators/operators.go
Labels: approved

#600 Tests for basenoidling tier
  test/e2e/nstemplatetier_test.go
  testsupport/tiers/checks.go
Labels: approved

#606 Provide more operator installation information during perf setup
  setup/operators/installtemplates/kiali.yaml
  setup/operators/operators.go
Labels: approved

#610 Update perf tool to use base1ns tier
  setup/README.adoc
  setup/cmd/root.go
  setup/configuration/configuration.go
  setup/idlers/update_idler.go
  setup/operators/installtemplates/devspaces.yaml
  setup/resources/create_resources.go
Labels: approved

#611 Update tests for RHODS single namespace test.
  testsupport/tiers/checks.go
Labels: approved, ok-to-test
