Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2022-05, with the labels that each got.

#549 fix(appstudio): use latest tag in CI
  make/appstudio.mk
  make/dev.mk
  test/e2e/space_autocompletion_test.go
Labels: approved

#553 refactor: drop SignupRequest interface
  testsupport/signup_request.go
Labels: approved

#554 refactor(err): insert space between message and details
  test/e2e/parallel/registration_service_test.go
Labels: approved

#550 Test deactivation controller with UserTiers
  test/e2e/e2e_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/parallel/registration_service_test.go
  test/e2e/proxy_test.go
  test/e2e/user_management_test.go
  test/e2e/usersignup_test.go
  test/migration/verify/verify_migration_test.go
  testsupport/deactivation.go
  testsupport/signup_request.go
  testsupport/tiers/tier_setup.go
  testsupport/user_assertions.go
Labels: approved

#551 chore: check go.mod replacement only when needed
  .github/workflows/ci-build.yml
  .github/workflows/ci-check-gomod-alt.yml
  .github/workflows/ci-check-gomod.yml
Labels: approved

#555 refactor(test): simplify token generation
  test/e2e/parallel/registration_service_test.go
  test/e2e/user_management_test.go
  testsupport/auth/token_generator.go
  testsupport/signup_request.go
Labels: approved

#556 Chore: Add empty metrics instance for appstudio
  setup/metrics/gather.go
Labels: approved, lgtm, ok-to-test

#557 test: restore method comments
  testsupport/signup_request.go
Labels: approved

#558 check user has spiaccesscheck permissions in the namespace
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#547 Added migration test
  test/e2e/usersignup_test.go
Labels: approved
