Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2023-09, with the labels that each got.

#791 disable phone verification in dev & appstudio environments
  deploy/host-operator/appstudio-dev/toolchainconfig.yaml
  deploy/host-operator/appstudio-e2e/toolchainconfig.yaml
  deploy/host-operator/dev/toolchainconfig.yaml
Labels: approved, lgtm

#785 feat: update SpaceBinding cleanup controller to delete SBR resources
  test/e2e/parallel/space_cleanup_test.go
  testsupport/wait/member.go
Labels: approved

#792 feat: make SpaceBindingRequest.Spec.MasterUserRecord immutable
  test/e2e/parallel/spacebindingrequest_test.go
  testsupport/wait/member.go
Labels: approved

#794 resources: increase the PVC claim limit to 30
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#795 Add note about idler configuration
  setup/README.adoc
Labels: approved, needs-ok-to-test

#798 verify that conflicts with Space names are being checked for compliantUsername
  test/e2e/parallel/registration_service_test.go
  test/e2e/user_management_test.go
  test/e2e/usersignup_test.go
Labels: approved

#799 CRC console doesn't contain .apps. substring
  test/e2e/parallel/registration_service_test.go
Labels: approved

#796 Update e2e tests to confirm PropagatedClaims are propagated
  go.mod
  go.sum
  test/e2e/nstemplatetier_test.go
  test/migration/setup_runner.go
  testsupport/user_assertions.go
  testsupport/user_setup.go
Labels: approved

#800 fix: allow insecure clusters
  README.adoc
  testsupport/init.go
  testsupport/space/spacerequest.go
  testsupport/util/kube_client.go
  testsupport/wait/host.go
Labels: approved, lgtm, ok-to-test
