Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2023-10, with the labels that each got.

#797 feat: Implement public API that will open SpaceBindings to end users through proxy part 1
  go.mod
  go.sum
  test/e2e/proxy_test.go
Labels: approved

#804 Network policy for cnv
  testsupport/tiers/checks.go
Labels: approved

#802 Support regexp filter for tests that needs to run
  README.adoc
  make/test.mk
Labels: approved, lgtm, ok-to-test

#806 Removing --all option from oc get command
  make/clean.mk
Labels: approved, ok-to-test

#808 Update documentation for usage with quay.io
  quay.adoc
Labels: approved, needs-ok-to-test

#811 ci: bump actions to silence node12 warnings
  .github/workflows/ci-build.yml
  .github/workflows/ci-check-gomod.yml
  .github/workflows/publish-operators-for-e2e-tests.yml
Labels: approved, lgtm, ok-to-test

#810 fix: enable webhook test check for sbr
  testsupport/wait/member.go
Labels: approved

#813 add test to confirm that propagatedclaims are correctly propagated al…
  test/e2e/usersignup_test.go
Labels: approved

#807 verify that targetClustersfor UserAccount is dynamically loaded
  go.mod
  go.sum
  test/e2e/e2e_test.go
  test/e2e/parallel/retarget_test.go
  test/e2e/parallel/space_test.go
  test/e2e/usersignup_test.go
  testsupport/signup_request.go
  testsupport/user_assertions.go
  testsupport/wait/host.go
  testsupport/wait/member.go
Labels: approved

#805 feat: Implement public API that will open SpaceBindings to end users through proxy part 2
  go.mod
  go.sum
  test/e2e/proxy_test.go
Labels: approved

#801 set approved to false after user sign up deactivated
  test/e2e/e2e_test.go
  test/e2e/parallel/registration_service_test.go
  test/e2e/user_management_test.go
  test/metrics/metrics_test.go
  testsupport/deactivation.go
  testsupport/wait/conditions.go
Labels: approved, ok-to-test

#817 drop printing all resources in host namespace
  testsupport/wait/host.go
Labels: approved, lgtm

#818 fix: binding request field should not be returned when empty
  go.mod
  go.sum
  test/e2e/proxy_test.go
Labels: approved

#819 add CODEOWNERS file
  CODEOWNERS
Labels: approved

#809 Add tests for VM webhook
  deploy/member-operator/e2e-tests/README.adoc
  deploy/member-operator/e2e-tests/kubevirt.io_virtualmachines.yaml
  test/e2e/parallel/vm_webhook_test.go
  test/migration/setup/setup_migration_test.go
  testsupport/wait/member.go
Labels: approved

#816 wait for proxy metrics service
  testsupport/init.go
Labels: approved

#822 Re-enable webhook checks on migration setup test
  test/migration/setup/setup_migration_test.go
  testsupport/wait/member.go
Labels: approved

#820 feat: add usernames endpoint in reg-service
  test/e2e/parallel/registration_service_test.go
  test/metrics/metrics_test.go
  testsupport/regsvc.go
Labels: approved

#821 Added test to ensure GetSignup endpoint updates IdentityClaims
  test/e2e/usersignup_test.go
  testsupport/regsvc.go
Labels: approved

#825 Increase resource quota for appstudio tier
  testsupport/tiers/checks.go
Labels: approved

#824 Check for additional CNV namespace policy
  testsupport/tiers/checks.go
Labels: approved

#828 Align resource quota in base tier with base1ns
  testsupport/tiers/checks.go
Labels: approved
