Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2023-08, with the labels that each got.

#766 drop obsolete proxy Role&RoleBinding
  test/e2e/proxy_test.go
  testsupport/tiers/checks.go
Labels: approved

#769 fix: SpaceRequest SA token generation doesn't keep in account of the member cluster
  test/e2e/parallel/spacerequest_test.go
Labels: approved

#770 Include go version as prereq for perf tool
  setup/README.adoc
Labels: approved

#768 address comments from PR #767
  test/e2e/parallel/serviceaccount_test.go
  testsupport/wait/member.go
Labels: approved

#771 feat: add support for SpaceBinding inheritance when there are multiple subspace levels
  test/e2e/parallel/space_test.go
Labels: approved

#773 feat: create SpaceBindingRequest controller skeleton
  deploy/host-operator/appstudio-dev/toolchainconfig.yaml
  deploy/host-operator/appstudio-e2e/toolchainconfig.yaml
  deploy/host-operator/e2e-tests/toolchainconfig.yaml
Labels: approved

#774 verify replacement of * by verbs in appstudio templates
  testsupport/tiers/checks.go
Labels: approved

#780 adds deletecollection verb to components and applications
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#779 feat: Implement SpaceBindingRequest controller main logic
  go.mod
  go.sum
  test/e2e/parallel/spacebindingrequest_test.go
  testsupport/spacebindingrequest.go
  testsupport/wait/host.go
  testsupport/wait/member.go
Labels: approved

#782 Update admin spacerole role and rolebinding to indicate level
  testsupport/tiers/checks.go
Labels: approved, lgtm, ok-to-test

#783 Let appstudio admins exec (rsh) to pods
  testsupport/tiers/checks.go
Labels: approved

#786 appstudio: verify limits of SpaceRequests and DT(C/S)s
  testsupport/tiers/checks.go
Labels: approved

#790 Fix & mention local targets, and remove quay username prefix
  dev_install.adoc
Labels: approved

#789 feat: grant edit permissions over SBRs to RHTAP admis
  testsupport/tiers/checks.go
Labels: approved
