Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2023-11, with the labels that each got.

#830 Add VM cloud init user data test
  test/e2e/parallel/vm_webhook_test.go
Labels: approved

#833 Add retry for metrics
  setup/metrics/gather.go
Labels: approved

#832 Introduce appstudio large tier
  test/e2e/nstemplatetier_test.go
  testsupport/tiers/checks.go
Labels: approved

#826 add migration assertions for space requests
  test/migration/setup_runner.go
  test/migration/verify/verify_migration_test.go
  testsupport/space/spacerequest.go
Labels: approved, lgtm

#838 Added migration test
  test/e2e/usersignup_test.go
Labels: approved

#835 Update tests to use config for vm webhook
  deploy/crds/README.adoc
  deploy/crds/appstudio.redhat.com_applications.yaml
  deploy/crds/appstudio.redhat.com_environments.yaml
  deploy/crds/kubevirt.io_virtualmachines.yaml
  deploy/host-operator/dev/toolchainconfig.yaml
  deploy/host-operator/e2e-tests/toolchainconfig.yaml
  deploy/member-operator/dev/secrets.yaml
  deploy/member-operator/e2e-tests/secrets.yaml
  make/test.mk
  test/e2e/parallel/vm_webhook_test.go
Labels: approved

#843 Fix issue for appstudio environment
  make/test.mk
Labels: approved, lgtm

#839 Removed migration code
  test/e2e/usersignup_test.go
Labels: approved

#836 Split WaitForDeployments
  test/migration/setup/setup_migration_test.go
  testsupport/init.go
Labels: approved, lgtm

#840 E2e tests for K8sImagePuller validating webhook
  testsupport/wait/member.go
Labels: approved, ok-to-test

#845 parallelize nstemplatetier test
  test/e2e/default_tier_test.go
  test/e2e/parallel/nstemplatetier_test.go
Labels: approved

#846 parallelize user rolebindings test
  test/e2e/parallel/user_rolebindings_test.go
Labels: approved

#847 extract non-parallelizable parts from e2e test
  test/e2e/e2e_test.go
  test/e2e/toolchainstatus_test.go
  test/metrics/metrics_test.go
Labels: approved

#849 extract test verifying skipped creation of user and identity
  test/e2e/no_user_identity_test.go
  test/e2e/proxy_test.go
Labels: approved

#848 parallelize user workload test
  test/e2e/parallel/user_workloads_test.go
Labels: approved

#853 Increase storage request limit for appstudo
  testsupport/tiers/checks.go
Labels: approved

#851 parallelize e2e test
  test/e2e/parallel/e2e_test.go
Labels: approved

#850 wait for deployments once
  test/e2e/parallel/web_console_plugin_test.go
  testsupport/init.go
Labels: approved

#852 parallelize proxy test
  test/e2e/parallel/proxy_test.go
Labels: approved, lgtm

#854 Update toolchain-common
  go.mod
  go.sum
  setup/cmd/root.go
  setup/operators/operators.go
  setup/operators/operators_test.go
  setup/resources/create_resources.go
  setup/resources/create_resources_test.go
  setup/templates/template.go
Labels: approved, lgtm

#857 Stop reusing connections
  testsupport/user_setup.go
Labels: approved

#834 create spacebinding migration test and fix migration test
  test/e2e/parallel/retarget_test.go
  test/e2e/parallel/space_test.go
  test/e2e/spacebindingrequest_migration_test.go
  test/migration/setup_runner.go
  testsupport/wait/member.go
Labels: approved

#855 Dropping the unused parameters
  go.mod
  go.sum
  testsupport/user_assertions.go
Labels: approved

#859 Temporarily extend deactivation
  test/e2e/user_management_test.go
  testsupport/init.go
  testsupport/wait/host.go
Labels: approved

#860 Revert "Temporarily extend deactivation (#859)"
  test/e2e/user_management_test.go
  testsupport/wait/host.go
Labels: approved

#858 Updated e2e tests for member operator - refactor UserAccountController to use PropagatedClaims
  testsupport/user_assertions.go
Labels: approved
