Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2023-05, with the labels that each got.

#720 Increase cpu request to 3 for base1ns tier
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#715 check if SpaceBinding is being deleted
  testsupport/wait/host.go
Labels: approved

#719 Test invalid proxy request headers
  test/e2e/nstemplatetier_test.go
  test/e2e/proxy_test.go
Labels: approved

#711 fix: Don't block Space deletion if it hasn't been provisiond to member cluster ye
  test/e2e/parallel/space_test.go
Labels: approved

#714 compliant username
  go.mod
  go.sum
  test/e2e/parallel/registration_service_test.go
  test/e2e/parallel/space_cleanup_test.go
  test/e2e/user_management_test.go
  test/e2e/usersignup_test.go
  test/migration/setup_runner.go
Labels: approved

#723 Remove starting CSVs to improve perf tooling setup
  setup/operators/installtemplates/devspaces.yaml
  setup/operators/installtemplates/devworkspace-operator.yaml
  setup/operators/installtemplates/gitops-primer-template.yaml
  setup/operators/installtemplates/kiali.yaml
  setup/operators/installtemplates/openvino.yaml
  setup/operators/installtemplates/rhoas.yaml
  setup/operators/installtemplates/sbo.yaml
  setup/operators/installtemplates/serverless-operator.yaml
  setup/operators/installtemplates/web-terminal-operator.yaml
Labels: approved

#724 make migration test usernames shorter
  test/migration/setup_runner.go
  test/migration/verify/verify_migration_test.go
  testsupport/space.go
Labels: approved, lgtm

#718 Add a dedicated service account to run Tekton pipelines
  make/clean.mk
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#722 fix: drop workspace label check from space testsupport
  testsupport/space.go
Labels: approved

#725 run verify functions with new operators in migration tests
  test/migration/verify/verify_migration_test.go
Labels: approved

#721 Added Workspace Name Label check
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#729 fix: add wait for NSTemplateSet to have space roles populated
  testsupport/tiers/nstemplateset.go
  testsupport/wait/member.go
Labels: approved

#727 Test user_signups_approved_with_method_total metric
  test/metrics/metrics_test.go
  testsupport/metrics.go
Labels: approved

#731 fix: use updated nstemplateset
  testsupport/tiers/nstemplateset.go
Labels: approved

#732 wait for SpaceRole when provisioning
  test/migration/setup_runner.go
  testsupport/tiers/nstemplateset.go
Labels: approved

#736 Check for new mem limit
  testsupport/tiers/checks.go
Labels: approved

#739 refactor: move conditions into 'testsupport/wait' pkg
  setup/idlers/update_idler.go
  test/e2e/e2e_test.go
  test/e2e/nstemplatetier_test.go
  test/e2e/parallel/registration_service_test.go
  test/e2e/parallel/serviceaccount_test.go
  test/e2e/parallel/space_cleanup_test.go
  test/e2e/parallel/space_test.go
  test/e2e/parallel/spacerequest_test.go
  test/e2e/parallel/web_console_plugin_test.go
  test/e2e/proxy_test.go
  test/e2e/space_autocompletion_test.go
  test/e2e/user_management_test.go
  test/e2e/user_rolebindings_test.go
  test/e2e/user_workloads_test.go
  test/e2e/usersignup_test.go
  test/metrics/metrics_test.go
  test/migration/setup_runner.go
  test/migration/verify/verify_migration_test.go
  testsupport/deactivation.go
  testsupport/metrics.go
  testsupport/signup_request.go
  testsupport/space.go
  testsupport/toolchain_status_assertions.go
  testsupport/user_assertions.go
  testsupport/wait/conditions.go
Labels: approved

#735 fix: invalid number of subSpaces issue
  test/e2e/parallel/spacerequest_test.go
  testsupport/wait/host.go
Labels: approved

#726 fix: replace "owner" label with "space" label
  go.mod
  go.sum
  test/e2e/e2e_test.go
  testsupport/tiers/checks.go
  testsupport/user_assertions.go
  testsupport/wait/member.go
Labels: approved

#738 remove woopra in paired PR
  deploy/host-operator/e2e-tests/toolchainconfig.yaml
  test/e2e/parallel/registration_service_test.go
Labels: approved

#741 Move to the new tekton sa
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#740 refactor: move logic related to metrics into 'HostAwaitility'
  test/e2e/toolchainstatus_test.go
  test/metrics/metrics_test.go
  testsupport/cleanup/clean.go
  testsupport/metrics.go
  testsupport/metrics/metrics.go
  testsupport/metrics_server_assertions.go
  testsupport/tiers/checks.go
  testsupport/tiers/tier_setup.go
  testsupport/wait/awaitility.go
  testsupport/wait/host.go
  testsupport/wait/member.go
Labels: approved

#733 e2e test changes for separate segment keys for devspaces and sandbox
  deploy/host-operator/e2e-tests/toolchainconfig.yaml
  go.mod
  go.sum
  test/e2e/parallel/registration_service_test.go
Labels: approved
