Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2023-04, with the labels that each got.

#696 upgrade golang version go1.18.8 in openshift-ci
  openshift-ci/Dockerfile.tools
Labels: approved

#697 Increase resource threshold for appstudio dev/e2e
  deploy/host-operator/appstudio-dev/toolchainconfig.yaml
  deploy/host-operator/appstudio-e2e/toolchainconfig.yaml
Labels: approved, lgtm, ok-to-test

#685 Implement creation of sub-spaces in SpaceRequest controller
  deploy/host-operator/appstudio-dev/toolchainconfig.yaml
  deploy/host-operator/appstudio-e2e/toolchainconfig.yaml
  deploy/host-operator/e2e-tests/toolchainconfig.yaml
  go.mod
  go.sum
  make/clean.mk
  test/e2e/parallel/space_cleanup_test.go
  test/e2e/parallel/spacerequest_test.go
  testsupport/space.go
  testsupport/spacerequest.go
  testsupport/util.go
  testsupport/wait/host.go
  testsupport/wait/member.go
Labels: approved

#699 fix: use ToolchainConfig in README
  dev_install.adoc
Labels: approved

#692 verify appstudio environment tier
  test/e2e/nstemplatetier_test.go
  testsupport/tiers/checks.go
  testsupport/tiers/nstemplateset.go
  testsupport/wait/member.go
  testsupport/wait/templateref_parser.go
  testsupport/wait/templateref_split.go
Labels: approved

#700 Provision sub-space to the same member clusters as parent space
  test/e2e/parallel/spacerequest_test.go
Labels: approved

#695 e2e tests for AppStudio Roles
  test/e2e/parallel/space_test.go
  testsupport/tiers/checks.go
Labels: approved

#694 upgrade Go 1.19 and k8s.io v0.25.0
  .github/workflows/ci-build.yml
  .github/workflows/publish-operators-for-e2e-tests.yml
  README.adoc
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
  required_tools.adoc
  setup/cmd/root.go
  setup/configuration/configuration.go
  setup/metrics/client.go
  setup/operators/operators_test.go
  setup/resources/create_resources_test.go
  setup/templates/template.go
  setup/wait/wait_test.go
  test/e2e/parallel/registration_service_test.go
  test/e2e/proxy_test.go
  test/e2e/user_management_test.go
  testsupport/metrics/metrics.go
  testsupport/signup_request.go
Labels: approved

#702 test: ensure metrics are back to baseline after test
  test/metrics/metrics_test.go
  testsupport/metrics.go
  testsupport/wait/awaitility.go
Labels: approved

#690 Add e2e test for web console plugin
  deploy/host-operator/e2e-tests/toolchainconfig.yaml
  test/e2e/web_console_plugin_test.go
  testsupport/signup_request.go
  testsupport/wait/member.go
Labels: approved

#701 feat(STONEINTG-343): set ResourceQuota for Appstudio CRDs
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#693 Add test for read access to additional Core GitOps APIs
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#703 fix: wait for space deletion, not MUR twice
  testsupport/cleanup/clean.go
Labels: approved, lgtm

#707 disable unkown-cluster-related test
  make/test.mk
  test/e2e/parallel/space_test.go
Labels: approved

#709 appstudio: set skipUserCreation to true
  deploy/host-operator/appstudio-dev/toolchainconfig.yaml
  deploy/host-operator/appstudio-e2e/toolchainconfig.yaml
Labels: approved

#704 improve message when UserSignup cleanup fails
  testsupport/cleanup/clean.go
Labels: approved

#712 Remove write access to all GitOpsDeployment* resources, from all roles
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#705 fix: get Space & SpaceBinding directly in a loop
  test/e2e/parallel/space_cleanup_test.go
  testsupport/wait/host.go
Labels: approved

#710 fix & improve WebConsolePlugin test
  make/test.mk
  test/e2e/e2e_test.go
  test/e2e/parallel/web_console_plugin_test.go
  test/e2e/web_console_plugin_test.go
  testsupport/init.go
  testsupport/metrics_server_assertions.go
  testsupport/signup_request.go
  testsupport/wait/awaitility.go
  testsupport/wait/member.go
Labels: approved

#716 PLNSRVCE-1167: add logs resource to tekton results RBAC
  testsupport/tiers/checks.go
Labels: approved, ok-to-test
