Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2024-09, with the labels that each got.

#873 use base1ns as default SpaceTier for e2e tests
  deploy/host-operator/e2e-tests/toolchainconfig.yaml
  test/e2e/no_user_identity_test.go
  test/e2e/parallel/e2e_test.go
  test/e2e/parallel/nstemplatetier_test.go
  test/e2e/parallel/proxy_test.go
  test/e2e/parallel/registration_service_test.go
  test/e2e/parallel/socialevent_test.go
  test/e2e/parallel/space_cleanup_test.go
  test/e2e/parallel/spacerequest_test.go
  test/e2e/parallel/user_workloads_test.go
  test/e2e/parallel/usersignup_test.go
  test/e2e/user_management_test.go
  test/e2e/usersignup_test.go
  test/migration/setup_runner.go
  test/migration/verify/verify_migration_test.go
  testsupport/deactivation.go
  testsupport/signup_request.go
  testsupport/tiers/tier_setup.go
  testsupport/user_assertions.go
  testsupport/wait/stringify_test.go
Labels: approved

#1012 Check that ToolchainCluster status is populated
  go.mod
  go.sum
  test/e2e/toolchaincluster_test.go
  testsupport/kubeconfig/kubeconfig.go
  testsupport/wait/awaitility.go
Labels: approved

#1044 Upgrade to the latest toolchain-common version
  go.mod
  go.sum
Labels: approved

#1046 Update the tests to not distinguish between member and host
  test/e2e/toolchaincluster_test.go
Labels: approved

#1045 add e2e tests for banneduser
  test/e2e/parallel/proxy_test.go
Labels: approved

#1047 remove -parallel flag
  make/test.mk
Labels: approved

#1048 Add a target to get unstuck after a failed e2e test run
  make/clean.mk
Labels: approved

#1050 remove references to add-cluster script
  make/test.mk
  multicluster_setup.adoc
Labels: approved

#1009 add tests for Public-Viewer
  test/e2e/parallel/proxy_test.go
  test/e2e/proxy_publicviewer_test.go
  testsupport/spacebinding/spacebinding.go
Labels: approved, do-not-merge/hold

#1051 bump api
  go.mod
  go.sum
Labels: approved

#1049 KUBESAW-192: Introduce a make command for pre-requisite of verify-replace script
  make/go.mk
Labels: approved

#1052 chore: remove Shane from CODEOWNERS
  CODEOWNERS
Labels: approved, lgtm
