Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2024-05, with the labels that each got.

#958 Remove old RHODS install from setup tool
  setup/operators/installtemplates/intel-aikit.yaml
  setup/operators/installtemplates/intel-openvino.yaml
  setup/operators/installtemplates/rhods.yaml
  setup/operators/operators.go
Labels: approved

#960 Add tests for rhoai network policies
  testsupport/tiers/checks.go
Labels: approved

#948 add viewer role for appstudio
  test/e2e/parallel/proxy_test.go
  testsupport/tiers/checks.go
Labels: approved

#963 Test updated quota for rhoai
  testsupport/tiers/checks.go
Labels: approved

#959 Adding e2e test cases for auto-approval domains
  make/test.mk
  test/e2e/usersignup_test.go
  testsupport/wait/conditions.go
  testsupport/wait/host.go
Labels: approved, ok-to-test

#965 test: SANDBOX-618 TestUpdateSpaceRequest - wait until the space has the desired number of namespaces
  test/e2e/parallel/spacerequest_test.go
  testsupport/wait/host.go
Labels: approved

#964 test: refactor CreateSpaceWithBinding function - create first Space and SpaceBinding and just after add them to the clean up task
  testsupport/space/space.go
Labels: approved, lgtm

#967 Remove OWNERS file
  OWNERS
  go.mod
  go.sum
Labels: approved

#970 KUBESAW-16: Label token secrets
  go.mod
  go.sum
  test/e2e/toolchaincluster_test.go
Labels: approved

#933 SANDBOX-554 tests for setting ScheduledDeactivationTime on UserSignup
  test/e2e/user_management_test.go
  testsupport/wait/conditions.go
  testsupport/wait/host.go
Labels: approved

#971 test: SANDBOX-624: TestForceMetricsSynchronization: EnsureMUR
  test/metrics/metrics_test.go
  testsupport/user_setup.go
Labels: approved

#973 Removing Michael's name from reviewers
  OWNERS
Labels: approved, lgtm

#978 flaky: fix invalid SBR before cleanup
  test/e2e/parallel/proxy_test.go
Labels: approved

#979 run metrics tests separate
  make/test.mk
Labels: approved

#980 fix flaky: copy ToolchainCluster secret
  test/e2e/toolchaincluster_test.go
Labels: approved

#982 Add rules for SecretStore and ExternalSecret CRs
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#987 Add ImageRepository CR permissions
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#976 KUBESAW-16: Make sure the toolchain cluster token secrets are labeled also in the member operator
  test/e2e/toolchaincluster_test.go
Labels: approved

#955 KUBESAW-43: Replace the special ToolchainClusterCondition with the standard toolchain Condition
  go.mod
  go.sum
  setup/users/create_users.go
  setup/users/create_users_test.go
  test/e2e/parallel/registration_service_test.go
  test/e2e/parallel/spacerequest_test.go
  test/e2e/toolchaincluster_test.go
  test/migration/verify/verify_migration_test.go
  testsupport/init.go
  testsupport/toolchain_status_assertions.go
  testsupport/user_assertions.go
  testsupport/wait/awaitility.go
Labels: approved

#988 Remove version from apiGroups
  testsupport/tiers/checks.go
Labels: approved, ok-to-test
