Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2024-06, with the labels that each got.

#989 fix flakiness: reset invalid SpaceRole to valid one in SBR
  test/e2e/parallel/spacebindingrequest_test.go
Labels: approved, lgtm

#950 Check for new member webhook config names
  make/test.mk
  testsupport/init.go
  testsupport/wait/member.go
Labels: approved

#992 fix: cut name only if it's longer
  test/e2e/toolchaincluster_test.go
Labels: approved, lgtm

#993 Fix flaky e2e test
  test/e2e/user_management_test.go
Labels: approved

#991 test: SANDBOX-629: drop Resources and also return space and token in Execute
  test/e2e/default_tier_test.go
  test/e2e/no_user_identity_test.go
  test/e2e/parallel/e2e_test.go
  test/e2e/parallel/nstemplatetier_test.go
  test/e2e/parallel/proxy_test.go
  test/e2e/parallel/registration_service_test.go
  test/e2e/parallel/retarget_test.go
  test/e2e/parallel/serviceaccount_test.go
  test/e2e/parallel/space_cleanup_test.go
  test/e2e/parallel/space_test.go
  test/e2e/parallel/spacebindingrequest_test.go
  test/e2e/parallel/usersignup_test.go
  test/e2e/parallel/web_console_plugin_test.go
  test/e2e/space_autocompletion_test.go
  test/e2e/user_management_test.go
  test/e2e/usersignup_test.go
  test/metrics/metrics_test.go
  test/migration/setup_runner.go
  testsupport/signup_request.go
  testsupport/space/space.go
  testsupport/user_setup.go
Labels: approved

#984 test: SANDBOX-629: refactor TestCreateSpaceBindingRequest and TestUpdateSpaceBindingRequest
  test/e2e/parallel/spacebindingrequest_test.go
  testsupport/signup_request.go
Labels: approved

#983 test: SANDBOX-629: refactor TestPromoteSpace
  test/e2e/parallel/space_test.go
Labels: approved

#986 test: SANDBOX-629: refactor CreateSpaceRequest
  testsupport/space/spacerequest.go
Labels: approved

#985 test: SANDBOX-629: refactor TestSpaceRoles and TestSubSpaces
  test/e2e/parallel/space_test.go
Labels: approved

#977 add tests to check that SpaceProvisionerConfig is only ready when the underlying ToolchainCluster is ready
  test/e2e/parallel/spaceprovisionerconfig_test.go
  test/e2e/toolchaincluster_test.go
  test/e2e/usersignup_test.go
  testsupport/wait/awaitility.go
Labels: approved

#994 verify that certificates are not used in ToolchainClusters
  test/e2e/toolchaincluster_test.go
Labels: approved

#999 Increase quotas in appstudio and appstudiolarge
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#990 test: SANDBOX-629: refactor TestSubSpaceInheritance
  test/e2e/parallel/space_test.go
  test/e2e/space_autocompletion_test.go
  testsupport/space/space.go
Labels: approved, lgtm

#1002 KUBESAW-124: Makefile target for dependency validations
  make/go.mk
Labels: approved

#997 Make sure kubeconfig is present in the ToolchainCluster secrets on the host cluster.
  test/e2e/toolchaincluster_test.go
  testsupport/space/spacerequest.go
  testsupport/util/kube_client.go
Labels: approved
