Repository codeready-toolchain/toolchain-e2e, pull requests merged in 2024-03, with the labels that each got.

#907 fix: use relative paths to resources only & move to deploy
  deploy/default-network-policies.yaml
  deploy/host-operator/default-spaceprovisionerconfig.yaml
  make/test.mk
Labels: approved

#906 print setting KUBECONFIG env var for local debug
  make/test.mk
Labels: approved

#895 Copy the SA token of sub-spaces only for specific tiers
  test/e2e/parallel/spacerequest_test.go
  testsupport/wait/member.go
Labels: approved

#908 RHTAPSRE-439: Test deployment of CA bundle configmap
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#909 chore: keeping our GitHub Actions up to date with Dependabot
  .github/dependabot.yml
  .github/workflows/ci-build.yml
  .github/workflows/publish-operators-for-e2e-tests.yml
  .golangci.yml
  setup/metrics/gather_test.go
  setup/wait/wait_test.go
  test/e2e/no_user_identity_test.go
  test/e2e/parallel/e2e_test.go
  test/e2e/parallel/nstemplatetier_test.go
  test/e2e/parallel/proxy_test.go
  test/e2e/parallel/registration_service_test.go
  test/e2e/parallel/retarget_test.go
  test/e2e/parallel/spaceprovisionerconfig_test.go
  test/e2e/parallel/user_rolebindings_test.go
  test/e2e/parallel/vm_webhook_test.go
  test/e2e/parallel/web_console_plugin_test.go
  test/e2e/user_management_test.go
  test/e2e/usersignup_test.go
  test/metrics/metrics_test.go
  testsupport/metrics/metrics.go
  testsupport/metrics/metrics_test.go
  testsupport/tiers/checks.go
  testsupport/user_assertions.go
  testsupport/wait/awaitility.go
  testsupport/wait/host.go
  testsupport/wait/member.go
Labels: approved, lgtm

#912 reflect changes in add-cluster.sh script
  make/test.mk
Labels: approved

#916 SANDBOX-555: clean up packages being imported more than once
  setup/operators/operators.go
  test/e2e/parallel/nstemplatetier_test.go
  test/migration/setup_runner.go
Labels: approved, lgtm, ok-to-test

#893 KSPACE-20: Drop the distinction between host & member ToolchainClusters
  go.mod
  go.sum
  test/e2e/parallel/registration_service_test.go
  test/e2e/parallel/spacerequest_test.go
  test/e2e/space_autocompletion_test.go
  test/e2e/toolchaincluster_test.go
  test/migration/verify/verify_migration_test.go
  testsupport/init.go
  testsupport/toolchain_status_assertions.go
  testsupport/user_assertions.go
  testsupport/wait/awaitility.go
  testsupport/wait/host.go
  testsupport/wait/member.go
Labels: approved

#918 SANDBOX-555: remove unnecessary assertions
  test/e2e/parallel/space_test.go
  test/e2e/parallel/spacebindingrequest_test.go
Labels: approved, lgtm, ok-to-test

#919 SANDBOX-555: remove unnecessary empty lines
  README.adoc
  setup/cmd/root.go
  setup/idlers/update_idler.go
  setup/operators/operators.go
  setup/resources/create_resources_test.go
  setup/results/results.go
  setup/templates/template.go
  setup/users/create_users_test.go
  setup/wait/wait_test.go
  test/e2e/parallel/e2e_test.go
  test/e2e/parallel/nstemplatetier_test.go
  test/e2e/parallel/proxy_test.go
  test/e2e/parallel/registration_service_test.go
  test/e2e/parallel/serviceaccount_test.go
  test/e2e/parallel/space_cleanup_test.go
  test/e2e/parallel/space_test.go
  test/e2e/parallel/spacebindingrequest_test.go
  test/e2e/parallel/spacerequest_test.go
  test/e2e/parallel/web_console_plugin_test.go
  test/e2e/toolchainstatus_test.go
  test/e2e/user_management_test.go
  test/e2e/usersignup_test.go
  test/metrics/metrics_test.go
  test/migration/setup/setup_migration_test.go
  testsupport/appstudio/api/v1alpha1/application_types.go
  testsupport/appstudio/api/v1alpha1/environment_types.go
  testsupport/init.go
  testsupport/tiers/checks.go
  testsupport/user_assertions.go
  testsupport/wait/awaitility.go
  testsupport/wait/diff_test.go
  testsupport/wait/host.go
Labels: approved, ok-to-test

#925 SANDBOX-555: remove unnecessary assertions
  test/e2e/parallel/e2e_test.go
Labels: approved, lgtm, ok-to-test

#926 Increase appstudio pods quota
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#928 fix: drop type label selector from ToolchainCluster list
  make/test.mk
Labels: approved

#915 SANDBOX-555: UserSignup test enhancement
  test/e2e/doc.go
  test/e2e/parallel/usersignup_test.go
  test/e2e/usersignup_test.go
Labels: approved, lgtm, ok-to-test

#930 Increase appstudio tier pvc quota
  testsupport/tiers/checks.go
Labels: approved, ok-to-test

#927 Use the gomod-check action from toolchain-cicd
  .github/workflows/ci-check-gomod.yml
Labels: approved

#929 remove leftover "type" label
  setup/users/create_users.go
  setup/users/create_users_test.go
Labels: approved, lgtm

#924 KSPACE-46: Use SpaceProvisionerConfig for space assignment
  deploy/host-operator/default-spaceprovisionerconfig.yaml
  go.mod
  go.sum
  test/e2e/parallel/spacerequest_test.go
  test/e2e/space_autocompletion_test.go
  test/e2e/usersignup_test.go
  testsupport/spaceprovisionerconfig/spaceprovisionerconfig.go
Labels: approved

#938 feat: check for Konflux new Project* CRs
  testsupport/tiers/checks.go
Labels: approved, ok-to-test
